[workspace]
members = ["desktop", "fullstack", "common"]
resolver = "2"

[package]
name = "VISP"
version = "0.1.0"
edition = "2021"
authors = ["Kristopher Ali <kristopher.ali.dev+visp@gmail.com>"]

[[bin]]
name = "fullstack"
path = "fullstack/src/main.rs"

[[bin]]
name = "desktop"
path = "desktop/src/main.rs"