# Dev
# dx serve --hot-reload --platform desktop --bin visp_desktop

# dx serve --hot-reload --bin visp_web

# Build Instructions
# dx build --bin visp_desktop --release or dx bundle --bin visp_desktop --features bundle --release

# dx build --bin visp_web --release or dx serve --bin visp_web --release

[workspace]
members = ["visp_common", "visp_desktop", "visp_web"]
default-members = ["visp_desktop", "visp_web"]
resolver = "2"

[workspace.package]
# name = "visp"
version = "0.1.0"
edition = "2021"
authors = ["Kristopher Ali <kristopher.ali.dev+visp@gmail.com>"]
description = "Video. Images. Sound. Post. VISP is an open source multimedia editor built entirely using Rust. It works on all Desktop and Mobile platforms. And you can integrate it with your favorite social media sites like YouTube and Instagram!"

[workspace.dependencies]
dioxus = { version = "0.4.3" }
dioxus-router = { version = "0.4.3" }
dioxus-web = { version = "0.4.3" }
dioxus-desktop = { version = "0.4.3" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Web
# dx build --features visp_web --release
# cargo run --features ssr --release

# Desktop
# dx serve --hot-reload --platform visp_desktop