[application]
name = "VISP" # App (Project) Name
default_platform = "web" # visp_desktop, web
out_dir = "dist" # `build` & `serve` dist path
asset_dir = "assets" # resource (assets) file folder

short_description = "Video. Image. Sound. Post. A versatile tool."
long_description = """
Video. Image. Sound. Post. VISP is an open source multimedia editor built entirely using Rust. It works on all Desktop and Mobile platforms. And you can integrate it with your favorite social media sites like YouTube and Instagram!
"""

[application.plugins]
available = true
required = []

[web.app]
title = "VISP - Video / Image / Sound / Post" # HTML title tag content

[web.watcher]
index_on_404 = true
reload_html = true # when watcher trigger, regenerate the `index.html`
watch_path = ["src"] # which files or dirs will be watcher monitoring

[bundle]
identifier = "com.quaintstudios.visp" # Bundle identifier
publisher = "Quaint Studios" # Bundle publisher

icon = ["assets/favicon.ico"] # Bundle icon
resources = ["assets/*"] # Bundle resources

copyright = "MIT License Copyright (c) 2023-2025 Quaint Studios LLC. All rights reserved." # Bundle copyright
category = "Multimedia" # Bundle category